In [1]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv("/content/healthcare_data_cleaning_dataset.csv")

In [4]:
df.head(5)

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
0,17270,35.0,Male,Bangalore,Hypertension,13,41010.0,1,2023-11-30
1,10860,21.0,Female,Hyderabad,Flu,11,12194.0,1,2023-02-23
2,15390,77.0,Female,Bangalore,Asthma,2,45086.0,0,2023-03-14
3,15191,79.0,Female,Mumbai,Asthma,13,40842.0,0,2023-08-01
4,15734,60.0,Female,Delhi,Asthma,1,9873.0,1,2023-06-20

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          5100 non-null   int64
 1   Age                 4500 non-null   float64
 2   Gender              5100 non-null   object
 3   City                5100 non-null   object
 4   Diagnosis           5100 non-null   object
 5   Hospital_Visits     5100 non-null   int64
 6   Treatment_Cost      4507 non-null   float64
 7   Insurance_Coverage  5100 non-null   int64
 8   Admission_Date      5100 non-null   object
dtypes: float64(2), int64(3), object(4)
memory usage: 358.7+ KB

In [ ]:
# answer1:-a)
df.isna().sum()

Patient_ID              0
Age                   600
Gender                  0
City                    0
Diagnosis               0
Hospital_Visits         0
Treatment_Cost        593
Insurance_Coverage      0
Admission_Date          0
dtype: int64

In [ ]:
#answer1 b):-

null_percentage=df.isnull().sum()/len(df)*100
print(missing_percent)

Patient_ID               0
Age                    600
Gender                   0
City                     0
Diagnosis                0
Hospital_Visits          0
Treatment_Cost         593
Insurance_Coverage       0
Admission_Date           0
missing_percent       5100
dtype: int64
123.3921568627451

In [ ]:
print(df.isnull().sum())
null_percentage=df.isnull().sum()/len(df)*100
print(null_percentage)

Patient_ID               0
Age                    600
Gender                   0
City                     0
Diagnosis                0
Hospital_Visits          0
Treatment_Cost         593
Insurance_Coverage       0
Admission_Date           0
missing_percent       5100
dtype: int64
Patient_ID              0.000000
Age                    11.764706
Gender                  0.000000
City                    0.000000
Diagnosis               0.000000
Hospital_Visits         0.000000
Treatment_Cost         11.627451
Insurance_Coverage      0.000000
Admission_Date          0.000000
missing_percent       100.000000
dtype: float64

In [ ]:
null_percentage

Patient_ID              0.000000
Age                    11.764706
Gender                  0.000000
City                    0.000000
Diagnosis               0.000000
Hospital_Visits         0.000000
Treatment_Cost         11.627451
Insurance_Coverage      0.000000
Admission_Date          0.000000
missing_percent       100.000000
dtype: float64

In [ ]:
null_percentage=df.isnull().sum()/len(df)*100
print(null_percentage)

Patient_ID              0.000000
Age                    11.764706
Gender                  0.000000
City                    0.000000
Diagnosis               0.000000
Hospital_Visits         0.000000
Treatment_Cost         11.627451
Insurance_Coverage      0.000000
Admission_Date          0.000000
missing_percent       100.000000
dtype: float64

In [ ]:
df['missing_percent']= null_percentage

In [ ]:
df.head(5)

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date,missing_percent
0,17270,35.0,Male,Bangalore,Hypertension,13,41010.0,1,2023-11-30,NaN
1,10860,21.0,Female,Hyderabad,Flu,11,12194.0,1,2023-02-23,NaN
2,15390,77.0,Female,Bangalore,Asthma,2,45086.0,0,2023-03-14,NaN
3,15191,79.0,Female,Mumbai,Asthma,13,40842.0,0,2023-08-01,NaN
4,15734,60.0,Female,Delhi,Asthma,1,9873.0,1,2023-06-20,NaN

In [ ]:
#anser2:-
#df[['Age', 'Treatment_Cost']].fillna(df[['Age', 'Treatment_Cost']].mean(), inplace=True)


# here mean is used to impute null values as the null values are  present at random that is there is
# no fixed pattern.  hence mean is used to impute as it will calculate the averafe of all the not null values irrespective of their pattern.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          5100 non-null   int64
 1   Age                 5100 non-null   float64
 2   Gender              5100 non-null   object
 3   City                5100 non-null   object
 4   Diagnosis           5100 non-null   object
 5   Hospital_Visits     5100 non-null   int64
 6   Treatment_Cost      5100 non-null   float64
 7   Insurance_Coverage  5100 non-null   int64
 8   Admission_Date      5100 non-null   object
 9   missing_percent     0 non-null      float64
dtypes: float64(3), int64(3), object(4)
memory usage: 398.6+ KB

In [ ]:
df.isna().sum()

Patient_ID               0
Age                    600
Gender                   0
City                     0
Diagnosis                0
Hospital_Visits          0
Treatment_Cost         593
Insurance_Coverage       0
Admission_Date           0
missing_percent       5100
dtype: int64

In [ ]:
# answer3:-
treatment_cost_medianValue=df['Treatment_Cost'].median()
print(treatment_cost_medianValue)

24797.0

In [ ]:
#ipute median value to the missing values in treatment_cost
df['Treatment_Cost'].fillna(df['Treatment_Cost'].median(), inplace=True)
# here median is used to impute treatment cost null values asTreatment cost is highly skewed due to expensive treatments."
using the mean could  inflate the imputed values. therefore median values will be used.

In [ ]:
#answer4:-a)
df.duplicated().sum()
doplicate_records_count=df.duplicated().sum()
print(doplicate_records_count)
print("the duplicates records in the starting are:-",doplicate_records_count)
datacount_initial= len(df)
print("the initial df size is:-",datacount_initial)

99
the duplicates records in the starting are:- 99
the initial df sizw is:- 5100

In [ ]:
# answer4:-b) removing duplicates from dataframe df
df.drop_duplicates(inplace=True)
print(df.duplicated().sum())
# answer4 c):-
print("the initial df size is:-",datacount_initial)
print("the size of dataframe df after removing duplicates is:-",len(df))

0
the initial df size is:- 5100
the size of dataframe df after removing duplicates is:- 5001

In [16]:
#answer5:-
# if the age value is unrealistic like if it greater than 100 or less than 0 then we havw to take care of iter
# to detect bfor age>100 and age<0

invalid_age_mask = (df['Age'] < 0) | (df['Age'] > 100)
print("no of invalid age",invalid_age_mask.sum())
invalid_records = df[invalid_age_mask]
print(f"Number of invalid age records: {len(invalid_records)}")

if invalid_age_mask.sum() > 0:
    print("there is invalid age record")
else:
    print("there is no invalid age record")

no of invalid age 0
Number of invalid age records: 0
there is no invalid age record

In [ ]:
df['Age']

0       35.0
1       21.0
2       77.0
3       79.0
4       60.0
        ...
4996     NaN
4997    35.0
4998    60.0
4999    16.0
5095     NaN
Name: Age, Length: 5001, dtype: float64

In [17]:
#answer6:-

# Calculate Q1, Q3, and IQR
Q1 = df['Treatment_Cost'].quantile(0.25)
Q3 = df['Treatment_Cost'].quantile(0.75)
#calculate iqr
IQR = Q3 - Q1

# defining boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# 3. Detect outliers
outliers = df[(df['Treatment_Cost'] < lower_bound) | (df['Treatment_Cost'] > upper_bound)]
print(f"Number of outliers detected using IQR: {len(outliers)}")

Number of outliers detected using IQR: 50

In [18]:
# anser:-8
# adding a new column  that is having the log of tratment_cost values
df['Log_Treatment_Cost'] = np.log1p(df['Treatment_Cost'])

# 2. to  Compare skewness before and after
skew_before = df['Treatment_Cost'].skew()
skew_after = df['Log_Treatment_Cost'].skew()
#printing the observation
print(f"Skewness before transformation: {skew_before}")
print(f"Skewness after log transformation: {skew_after}")

Skewness before transformation: 4.485699649227538
Skewness after log transformation: -1.1056582956857453

In [ ]:
#answer9:-

df['Admission_Date'] = pd.to_datetime(df['Admission_Date'])

# 2. Sort data by Admission_Date
df.sort_values(by='Admission_Date', inplace=True)

# 3. Applying  forward fill (ffill) to handle missing values sequentially
df.fillna(method='ffill', inplace=True)

****************** ASSIGNMENT ENDS****************